# T480s output config
output eDP-1 {
    mode 1920x1080@60.012Hz
    position 0,0
    bg #0a1628 solid_color
}

output DP-2 {
    mode 3440x1440@59.973Hz
    position 1920,0
    bg #0a1628 solid_color
}
